apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q3lmn7zup-python 
  janus-idp.io/tekton: q3lmn7zup-python
  backstage.io/kubernetes-id: q3lmn7zup-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q3lmn7zup-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml